server:
  port: 8085  # Puerto en el que se ejecutará la aplicación
  servlet:
    context-path: /api/v1  # Ruta base de la aplicación

spring:
  datasource:
    url: jdbc:mysql://autorack.proxy.rlwy.net:19025/recruitment_db
    username: root
    password: ZYIvJcEFkEkCghOiHNTdArjroSZKnbgv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    jwt:
      secret: clave_secreta

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  urls:
    - name: API SEEK
      url: https://pruebatecnicaseek-production.up.railway.app/api/v1/v3/api-docs

secretKeyJWT: H77iQbKExiQk9PdZ3fmQB8/1LzOAHc+C9134cHWLgpgxgQkQANciXZ2yS8p6bm4XtLY2ZI/XDgNzRym5V5Fjyg==
jackson:
  serialization:
    INDENT_OUTPUT: true

logging:
  level:
    root: INFO  # Nivel de logging para toda la aplicación
    com.example: DEBUG  # Nivel de logging específico para tu paquete
    org.springdoc: DEBUG

    org.springframework.data.mongodb: DEBUG  # Nivel de logging para Spring Data MongoDB
