server:
  port: 8085  # Puerto en el que se ejecutará la aplicación
  servlet:
    context-path: /api/v1  # Ruta base de la aplicación

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    jwt:
      secret: clave_secreta
secretKeyJWT: H77iQbKExiQk9PdZ3fmQB8/1LzOAHc+C9134cHWLgpgxgQkQANciXZ2yS8p6bm4XtLY2ZI/XDgNzRym5V5Fjyg==
jackson:
  serialization:
    INDENT_OUTPUT: true  # Formateo de salida JSON

logging:
  level:
    root: INFO  # Nivel de logging para toda la aplicación
    com.example: DEBUG  # Nivel de logging específico para tu paquete
    org.springframework.data.mongodb: DEBUG  # Nivel de logging para Spring Data MongoDB
